"""
SMARAN.AI — Windows EXE builder
===============================
Produces a standalone `SMARAN.AI.exe` that runs without Docker, Python, or a
sign-in. Everything the app needs (backend, prebuilt UI, dependencies) is
bundled into the executable.

Usage:
    python build_exe.py            # build the EXE
    python build_exe.py --onefile  # single-file EXE (slower first start)

Output:
    dist/SMARAN.AI/SMARAN.AI.exe   (default, folder build — fastest startup)
    dist/SMARAN.AI.exe             (--onefile)
"""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
APP_NAME = "SMARAN.AI"
ENTRY = os.path.join(ROOT, "desktop_app.py")
ICON = os.path.join(ROOT, "smaran.ico")
FRONTEND_DIST = os.path.join(ROOT, "backend", "frontend_dist")

# Packages PyInstaller cannot discover through dynamic imports.
def _write_analytics_config() -> None:
    """Bake the analytics endpoint and ingest key into the build.

    A frozen app cannot read the environment of the machine that built it,
    so the values have to become a module. The file is git-ignored: the key
    belongs in the binary, not in the repository.

    With nothing set the module is still written, empty, and reporting stays
    inert - which is what a build from a source checkout should do.
    """
    endpoint = os.getenv("SMARAN_ANALYTICS_URL", "").strip()
    key = os.getenv("SMARAN_ANALYTICS_KEY", "").strip()
    target = Path(__file__).parent / "backend" / "app" / "analytics_config.py"
    lines = [
        "# Generated by build_exe.py. Do not edit, do not commit.",
        f"ENDPOINT = {endpoint!r}",
        f"INGEST_KEY = {key!r}",
        "",
    ]
    target.write_text("\n".join(lines), encoding="utf-8")
    print("[build] analytics endpoint:", endpoint or "(none, reporting disabled)")

HIDDEN_IMPORTS = [
    "app.main",
    # Routers reached only through app.main. They are picked up by following
    # its imports, but naming them means a rename can never silently drop a
    # whole feature out of the build.
    "app.companion",
    "app.app_lock",
    "app.web_intents",
    "app.analytics_config",
    "app.password_policy",
    "app.updates",
    "app.desktop_agent",
    "app.plugin_routes",
    "app.sites_routes",
    "app.local_engine",
    # MCP is registered inside a try, so a static scan does not follow it.
    # Without these the packaged build silently has no MCP support at all.
    "app.mcp",
    "app.mcp.client",
    "app.mcp.manager",
    "app.mcp.routes",
    # Video is imported the same way. It needs torch, which this build
    # excludes on purpose, so the router registers and then reports that
    # PyTorch is not installed - which is true and is what should be said.
    "app.video",
    "app.video.hardware",
    "app.video.registry",
    "app.video.planner",
    "app.video.routes",
    "app.video.install",
    "app.capability",
    "app.tts",
    "app.tts.kokoro",
    "app.imaging",
    "app.imaging.registry",
    "app.imaging.engine",
    "app.imaging.routes",
    "app.media",
    "app.media.extract",
    "app.media.routes",
    # QR rendering. The import sits inside the endpoint so the module loads
    # without it, which also meant PyInstaller's static scan never saw it and
    # the packaged build shipped without the library.
    "segno",
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
    "webview",
    "webview.platforms.winforms",
    "edge_tts",
    "passlib.handlers.bcrypt",
    "sqlalchemy.dialects.sqlite",
    "email_validator",
]

def _ensure_nltk_data() -> None:
    r"""Fetch the corpora g2p-en needs, so the build does not depend on luck.

    --collect-all g2p_en gathers whatever nltk data is already on the machine.
    On the machine these builds were made on, cmudict and the tagger happened
    to be in %APPDATA%\nltk_data because something had downloaded them once.
    On a clean machine - a new laptop, a CI runner - they are not there, the
    build succeeds anyway, and the installer ships an offline voice that
    cannot start. That is the same class of silent gap as the missing
    onnxruntime extension, so it is closed the same way: the build fetches
    what it needs instead of assuming.
    """
    try:
        import nltk
    except ImportError:
        print("[build] nltk is not installed; the offline voice will not work "
              "in this build.")
        return

    for package, probe in (("cmudict", "corpora/cmudict"),
                           ("averaged_perceptron_tagger", "taggers/averaged_perceptron_tagger"),
                           ("averaged_perceptron_tagger_eng", "taggers/averaged_perceptron_tagger_eng")):
        try:
            nltk.data.find(probe)
        except LookupError:
            print(f"[build] fetching nltk {package}...")
            try:
                nltk.download(package, quiet=True)
            except Exception as exc:
                print(f"[build] could not fetch {package}: {exc}")


def _extra_binaries() -> list:
    """Native modules PyInstaller's own hooks fail to find.

    onnxruntime's hook asks for onnxruntime.capi.onnxruntime_pybind11_state
    as a hidden import and the build log answers:

        ERROR: Hidden import 'onnxruntime.capi.onnxruntime_pybind11_state'
        not found

    It carries on and produces a build with onnxruntime's DLLs but without
    the .pyd that `import onnxruntime` actually needs, so the import fails at
    runtime in a way nothing at build time complains about.

    That one missing file was both voice failures. Dictation asks
    faster-whisper to run with vad_filter=True, and its voice-activity filter
    needs onnxruntime - so every attempt ended in "Applying the VAD filter
    requires the onnxruntime package" and came back as an empty transcript.
    The offline voice needs it too.

    Located rather than hardcoded: a path written down here would be this
    machine's, and would rot the moment Python moved.
    """
    found = []
    try:
        import onnxruntime

        capi = os.path.join(os.path.dirname(onnxruntime.__file__), "capi")
        for name in os.listdir(capi):
            if name.endswith(".pyd"):
                found.append((os.path.join(capi, name), os.path.join("onnxruntime", "capi")))
    except Exception as exc:
        print(f"[build] onnxruntime binaries not located ({exc}); "
              "the offline voice and dictation will not work in this build.")
    return found


# Packages that ship data files / metadata they read at runtime.
COLLECT_ALL = [
    "chromadb",
    "faster_whisper",
    "deep_translator",
    "tokenizers",
    "tiktoken_ext",
    # The offline voice. Both are installed in the build environment and
    # neither was being collected, so the packaged app reported
    # "text-to-speech-offline: needs onnxruntime and g2p-en" and Speak fell
    # back to the online voice - which is why speaking worked from source and
    # not from the installer. onnxruntime also carries native libraries that
    # only --collect-all brings along.
    "onnxruntime",
    "g2p_en",
]

# Optional heavy dependencies that ChromaDB advertises but SMARAN.AI never uses:
# embeddings run through Ollama, and no local model is executed in-process.
# Excluding them removes roughly a gigabyte from the bundle.
EXCLUDES = [
    # The AWS SDK is never imported by this app; PyInstaller only picks it up
    # transitively. It also ships thousands of deeply nested data files whose
    # paths overflow the Windows 260-character limit, which aborted the
    # installer compile part-way through botocore's endpoint rule sets.
    "boto3",
    "botocore",
    "s3transfer",
    "torch",
    "torchvision",
    "torchaudio",
    "transformers",
    "polars",
    "faiss",
    "sklearn",
    "scikit-learn",
    "onnxruntime",
    "tensorflow",
    "matplotlib",
    "IPython",
    "notebook",
    "pytest",
    "PyInstaller",
]


def _ensure_frontend_built() -> None:
    index = os.path.join(FRONTEND_DIST, "index.html")
    if os.path.isfile(index):
        return
    print("[build] frontend_dist missing — building the UI first...")
    subprocess.run(["npx", "vite", "build"], cwd=os.path.join(ROOT, "frontend"),
                   check=True, shell=os.name == "nt")


def build(onefile: bool = False) -> int:
    _ensure_frontend_built()

    # Windows keeps a handle on a directory that any process has as its
    # working directory, even after that directory is emptied - a shell left
    # sitting in dist/SMARAN.AI is enough. rmtree here ignores the failure,
    # but PyInstaller then tries to remove the same folder itself and does
    # not, so the whole build ended with WinError 32 and produced nothing.
    #
    # Emptying the folder always works even when removing it does not, so the
    # contents go first. PyInstaller is then given somewhere it can write.
    for stale in ("build", "dist"):
        path = os.path.join(ROOT, stale)
        if not os.path.isdir(path):
            continue
        for entry in os.listdir(path):
            target = os.path.join(path, entry)
            if os.path.isdir(target):
                shutil.rmtree(target, ignore_errors=True)
                # A locked subdirectory survives; empty it in place.
                if os.path.isdir(target):
                    for inner in os.listdir(target):
                        inner_path = os.path.join(target, inner)
                        if os.path.isdir(inner_path):
                            shutil.rmtree(inner_path, ignore_errors=True)
                        else:
                            try:
                                os.remove(inner_path)
                            except OSError:
                                pass
            else:
                try:
                    os.remove(target)
                except OSError:
                    pass
        shutil.rmtree(path, ignore_errors=True)

    # PyInstaller replaces its output directory, and a directory Windows holds
    # a handle on cannot be replaced - a shell left sitting in dist/SMARAN.AI
    # is enough to keep that handle open, and the whole build then ends with
    # WinError 32 having produced nothing. So it is given a scratch folder of
    # its own and the result is copied into place afterwards: copying into the
    # locked folder works even though removing it does not.
    scratch = os.path.join(ROOT, "build", "_dist")
    shutil.rmtree(scratch, ignore_errors=True)

    sep = ";" if os.name == "nt" else ":"
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath", scratch,
        "--windowed",                      # no console window
        "--name", APP_NAME,
        "--onefile" if onefile else "--onedir",
        # Bundle the backend package and the prebuilt UI.
        "--paths", os.path.join(ROOT, "backend"),
        "--add-data", f"{FRONTEND_DIST}{sep}frontend_dist",
    ]

    if os.path.isfile(ICON):
        cmd += ["--icon", ICON]

    for source, destination in _extra_binaries():
        cmd += ["--add-binary", f"{source}{sep}{destination}"]

    for module in HIDDEN_IMPORTS:
        cmd += ["--hidden-import", module]
    for package in COLLECT_ALL:
        cmd += ["--collect-all", package]
    for package in EXCLUDES:
        cmd += ["--exclude-module", package]

    cmd.append(ENTRY)

    _write_analytics_config()
    _ensure_nltk_data()
    print("[build] running PyInstaller...")
    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode == 0:
        # Into the place the installer and everything else expect.
        produced = os.path.join(scratch, APP_NAME)
        final = os.path.join(ROOT, "dist", APP_NAME)
        os.makedirs(final, exist_ok=True)
        if os.path.isdir(produced):
            for entry in os.listdir(produced):
                source = os.path.join(produced, entry)
                target = os.path.join(final, entry)
                if os.path.isdir(source):
                    shutil.copytree(source, target, dirs_exist_ok=True)
                else:
                    shutil.copy2(source, target)
        elif os.path.isfile(produced + ".exe"):
            shutil.copy2(produced + ".exe",
                         os.path.join(ROOT, "dist", APP_NAME + ".exe"))
        shutil.rmtree(scratch, ignore_errors=True)

    if result.returncode != 0:
        print("[build] FAILED", file=sys.stderr)
        return result.returncode

    target = (os.path.join(ROOT, "dist", f"{APP_NAME}.exe") if onefile
              else os.path.join(ROOT, "dist", APP_NAME, f"{APP_NAME}.exe"))
    print(f"[build] done -> {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(build(onefile="--onefile" in sys.argv))
