"""Serving a generated picture, and refusing anything that is not one.

The image jobs finished, wrote a PNG and reported a path on disk, and there
was no route that would hand that file to a browser - the video module had
had one for a while and images had nothing. So a picture generated by the app
could not be displayed by the app, and the only way to see one was to open the
data folder.

The route takes an id from the URL and joins it onto a directory, which is the
shape of every path-traversal bug ever written. It is checked against the
pattern the generator actually produces - twelve hex characters - rather than
sanitised, because a whitelist cannot be talked round.
"""

import os
import sys
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

BACKEND = Path(__file__).resolve().parents[1]
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

# A real 1x1 PNG, so FileResponse has something valid to send.
PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4"
    "890000000a49444154789c6360000002000100ffff03000006000557bfabd400"
    "00000049454e44ae426082"
)


@pytest.fixture
def client(tmp_path, monkeypatch):
    from app.config import settings
    from app.imaging import routes

    monkeypatch.setattr(settings, "DATA_DIR", str(tmp_path))
    app = FastAPI()
    app.include_router(routes.router)
    return TestClient(app, raise_server_exceptions=False)


def place(tmp_path, job_id, data=PNG):
    folder = tmp_path / "images"
    folder.mkdir(exist_ok=True)
    (folder / f"{job_id}.png").write_bytes(data)


def test_a_finished_picture_is_served(client, tmp_path):
    place(tmp_path, "abcdef123456")
    res = client.get("/api/image/file/abcdef123456")
    assert res.status_code == 200
    assert res.headers["content-type"] == "image/png"
    assert res.content == PNG


def test_an_id_that_has_no_file_is_a_404_not_a_crash(client):
    assert client.get("/api/image/file/abcdef123456").status_code == 404


@pytest.mark.parametrize("job_id", [
    "../../../etc/passwd",
    "..%2f..%2fsecrets",
    "abcdef12345",          # eleven characters
    "abcdef1234567",        # thirteen
    "ABCDEF123456",         # uppercase is not what the generator makes
    "abcdefg12345",         # 'g' is not hex
    "....//....//x",
])
def test_anything_that_is_not_a_job_id_is_refused(client, job_id, tmp_path):
    """The id is joined onto a directory, so the check is a whitelist."""
    res = client.get(f"/api/image/file/{job_id}")
    assert res.status_code == 404


def test_a_traversal_cannot_reach_a_real_file_outside_the_folder(client, tmp_path):
    """Named separately because the one above only proves the status code.

    A secret is placed where a naive join would find it, and the route is
    asked for it by every spelling that would work if the id were trusted.
    """
    (tmp_path / "secret.txt").write_text("not for the web")
    place(tmp_path, "abcdef123456")
    for attempt in ("../secret.txt", "..%5csecret.txt", "%2e%2e%2fsecret.txt"):
        res = client.get(f"/api/image/file/{attempt}")
        assert res.status_code == 404
        assert b"not for the web" not in res.content


def test_the_route_reads_the_data_directory_it_is_told_about(client, tmp_path):
    """Not a hardcoded path: the app moves its data folder between installs."""
    place(tmp_path, "0123456789ab")
    assert client.get("/api/image/file/0123456789ab").status_code == 200
    os.remove(tmp_path / "images" / "0123456789ab.png")
    assert client.get("/api/image/file/0123456789ab").status_code == 404
