# -*- mode: python ; coding: utf-8 -*-

# Bake the analytics endpoint and key into the build.
#
# A frozen binary cannot read the environment of the machine that built it,
# so the values have to become a module - the same reason build_exe.py does
# this for the desktop app. Written empty when nothing is set, which is what
# a source checkout should produce: a build that reports nothing.
import os
from pathlib import Path

_endpoint = os.getenv('SMARAN_ANALYTICS_URL', '').strip()
_key = os.getenv('SMARAN_ANALYTICS_KEY', '').strip()
Path(SPECPATH, 'smaran_cli', 'analytics_config.py').write_text(
    '# Generated by smaran.spec. Do not edit, do not commit.\n'
    f'ENDPOINT = {_endpoint!r}\n'
    f'INGEST_KEY = {_key!r}\n',
    encoding='utf-8',
)
print('[cli build] analytics endpoint:', _endpoint or '(none, reporting disabled)')

a = Analysis(
    ['entry.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['smaran_cli.analytics_config'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='smaran',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
